services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_serving_php
    ports:
      - "8080:80"
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./logs:/var/www/html/logs
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=file_serving_db
      - DB_USER=root
      - DB_PASS=root
      - JWT_SECRET=your_random_jwt_secret_32_chars_minimum
      - UPLOAD_DIR=/var/www/html/uploads
    depends_on:
      - db
    networks:
      - file-serving-network

  db:
    image: mysql:8.0
    container_name: file_serving_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=file_serving_db
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - file-serving-network

volumes:
  db_data:
  uploads:
  logs:

networks:
  file-serving-network:
    driver: bridge